apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-keys
  labels:
    {{- include "..labels" . | nindent 4 }}
    component: haproxy
data:
{{ (tpl (.Files.Glob (printf "conf/haproxy/%s/%s/public.pem" .Values.environment .Values.phase)).AsConfig .) | indent 2 }}

