{{ if .Values.cnpgOldData.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cnpgOldData.fullname }}
  labels:
    {{- include "..labels-cnpg-old-data" . | nindent 4 }}
spec:
  startDelay: 300
  instances: 1

  storage:
    size: {{ .Values.cnpgOldData.storageSize | default "8Gi" | quote }}
  {{- if .Values.cnpgOldData.resources }}
  resources:
    {{- .Values.cnpgOldData.resources | toYaml | nindent 4 }}
  {{- end }}
  
  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-old-data-superuser

{{- end }}