apiVersion: v1
kind: ConfigMap
metadata:
  name: pgrest-config
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  PGRST_ADMIN_SERVER_PORT: {{ .Values.pgrest.serviceAdmin.port | quote }}
  PGRST_DB_ANON_ROLE: {{ .Values.pgrest.anonRole | quote }}
  PGRST_LOG_LEVEL: {{ .Values.pgrest.loglevel | quote }}
  PGRST_JWT_SECRET_IS_BASE64: "false"
  {{ with index .Values.pgrest.ingress.hosts 0 }}
  PGRST_OPENAPI_SERVER_PROXY_URI: {{ printf "https://%s" .host | quote }}
  {{ end }}
